sudo: required
language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-node-restify-aws-swagger' ]; then cd .. && eval "mv $currentfolder generator-node-restify-aws-swagger" && cd generator-node-restify-aws-swagger; fi

